server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
#  servlet:
#    context-path: /woju
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    suffix: .html
    check-template-location: true
    template-loader-path: classpath:/templates
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    request-context-attribute: request
    settings:
      default_encoding: UTF-8
      classic_compatible: true
      whitespace_stripping: true
      output_encoding: UTF-8
      url_escaping_charset: UTF-8
      tag_syntax: auto_detect
      locale: zh_CN
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      number_format: 0.##
      boolean_format: true,false
      auto_import: /le.html as le
    allow-request-override: false

mybatis-plus:
  mapper-locations: classpath*:com/le/**/*/mapper/xml/*.xml
  type-aliases-package: com.le.**.entity
  type-enums-package: com.le.**.enums
  global-config:
    db-config:
      id-type: ID_WORKER
      logic-delete-value: 1
      logic-not-delete-value: 0
    refresh: true
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
    config: classpath:config/logback-longe.xml
    path: longe-logs
longe:
    orderUrl: http://192.168.100.190/aisheli/oms/api/lucky/draw/getNo.jhtml

---

spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.180:3306/lucky-draw?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 666666
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000ms
    password:
  mail:
    host: smtp.qq.com
    username: 764252907@qq.com
    password: dnnzingoypzebfhg
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        starttls:
          enable: true  
          required: true
        debug: true
    default-encoding: UTF-8
    port: 587
---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/biaoben?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000ms
    password:
  mail:
    host: smtp.qq.com
    username: 764252907@qq.com
    password: dnnzingoypzebfhg
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        starttls:
          enable: true  
          required: true
        debug: true
    default-encoding: UTF-8
    port: 587

---

spring:
  profiles: produce
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/biaoben?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 666666
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000ms
    password:
  mail:
    host: smtp.qq.com
    username: 764252907@qq.com
    password: dnnzingoypzebfhg
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        starttls:
          enable: true  
          required: true
        debug: true
    default-encoding: UTF-8
    port: 587